### ISSUE TITLE
Transaction method time parameter

### ISSUE THREAD

**Issue by mayeaux** [gferrin/quadrigacx#3]
Do we know what the right way to format time requests on transactions is?

'time : hour' works

but how do we do 2 hours +? Their docs are pretty lacking. Thanks!

**Comment by gferrin** [comment]
Not sure sorry, but yeah their API is quite confusing. If you reach out to them though, they generally take a while to get back to you but are nice/helpful when they do.

**Comment by mayeaux** [comment]
Just got word back from the author of the Ruby QuadrigaCX API that 'hour' and 'minute' are the only two acceptable parameters that can be passed. Very weird.
